In [1]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D NumPy Array")
print("Shape:", arr_1d.shape)
print("Size:", arr_1d.size)
print("Dimension:", arr_1d.ndim)
print("Length:", len(arr_1d))

1D NumPy Array
Shape: (5,)
Size: 5
Dimension: 1
Length: 5


In [2]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D NumPy Array")
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimension:", arr_2d.ndim)
print("Length:", len(arr_2d))


2D NumPy Array
Shape: (3, 3)
Size: 9
Dimension: 2
Length: 3


In [3]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D NumPy Array")
print("Shape:", arr_3d.shape)
print("Size:", arr_3d.size)
print("Dimension:", arr_3d.ndim)
print("Length:", len(arr_3d))


3D NumPy Array
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2


In [4]:
import numpy as np
arr = np.arange(10)

In [12]:
arr = np.random.randint(10, 50, size=(2, 3))

In [6]:
arr = np.random.rand(2, 3)

In [7]:
arr = np.linspace(0, 10, 100)

In [8]:
arr = np.ones((2, 3), dtype=int)

In [9]:
arr = np.zeros((2, 3), dtype=int)

In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(np.diag(arr))

[1 5 9]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(np.min(arr))

1


In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(np.max(arr))

5


In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(arr))

5.5


In [17]:
import numpy as np
student_marks = np.random.randint(0, 100, 10)
fail_criteria = 30
no_of_students_passed = np.sum(student_marks >= fail_criteria)
failed_marks = student_marks[student_marks < fail_criteria]
print("Student marks:")
print(student_marks)
print("Number of students passed: ", no_of_students_passed)
print("Failed marks:")
print(failed_marks)

Student marks:
[24 52 13 87  4 89 51 77  6  7]
Number of students passed:  5
Failed marks:
[24 13  4  6  7]


In [18]:
import numpy as np
arr = np.random.randint(1, 51, size=(5, 5))
print(arr)

[[ 4 12 41 40 19]
 [45 42 36  4 25]
 [ 2 48 41 48 28]
 [44 28 43 20  5]
 [33 31 10 14 22]]


In [19]:
import numpy as np
odd_array = np.arange(-30, 10, 2)
print(odd_array)
Indices_list = np.where(np.mod(odd_array, 2) != 0)[0]
print("Indices list Odd elements is : ", Indices_list)

[-30 -28 -26 -24 -22 -20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4
   6   8]
Indices list Odd elements is :  []
